ids = {
    "portfolio_ret_page": {
        "PORTFOLIO_RET_PAGE_URL": "portfolio_ret_page_url",
        "PORTFOLIO_INFO_STORE": "portfolio_info_store",
        "PORTFOLIO_TYPE_DROPDOWN": "portfolio_type_dropdown",
        "PORTFOLIO_NAME_DROPDOWN": "portfolio_name_dropdown",
        "PORTFOLIO_RETURN_GRAGH": "portfolio_return_graph",
        "PORTFOLIO_START_PICKER": "portfolio_start_picker",
        "PORTFOLIO_END_PICKER": "portfolio_end_picker",
        "PORTFOLIO_RET_STORE": "portfolio_ret_store",
        "PORTFILIO_DATES_STORE": "portfolio_dates_store",
        "PORTFOLIO_DATES_NAME": "portfolio_dates_name",
        "PORTFOLIO_PERFORMANCE_TABLE": "portfolio_performance_table",
        "PORTFOLIO_DRAWDOWN": "portfolio_dropdown",
        "PORTFOLIO_RET_DOWNLOAD_BUTTON": "portfolio_ret_download_button",
        "PORTFOLIO_RET_DOWNLOAD": "portfolio_ret_download",
        "PORTFOLIO_RET_RADIO_ITEM": "portfolio_ret_radio_item",
        "PORTFOLIO_RET_PERFORMANCE_TABLE_2": "portfolio_ret_performance_table_2",
        "PORTFOLIO_RET_PERFORMANCE_STORE": "portfolio_ret_performance_store",
        "PORTFOLIO_RET_RADIO_TYPE_ITEM": "portfolio_ret_radio_type_item",
        "PORTFOLIO_ATTRIBUTE_TOTAL_RET": "portfolio_attribute_abs_ret",
        "PORTFOLIO_ATTRIBUTE_ALPHA": "portfolio_attribute_alpha",
        "PORTFOLIO_ATTRIBUTE_FUND": "portfolio_attribute_fund",
        "PORTFOLIO_ATTRIBUTE_BUTTON": "portfolio_attribute_button",
    },
    "portfolio_info_page": {
        "PORTFOLIO_INFO_TABLE": "portfolio_info_table",
    },
    "fund_score_page": {
        "FUND_SCORE_TABLE": "fund_score_table",
        "FUND_SCORE_DOWNLOAD_BUTTON": "fund_score_download_button",
        "FUND_SCORE_DOWNLOAD": "fund_score_download",
        "FUND_SCORE_QUERY_BUTTON": "fund_score_query_button",
    },
}
